/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log in
     * @description Authenticate and issue a session.
     *
     *     No body: everything the client needs is in the two cookies, and returning
     *     the user here would duplicate `GET /auth/me` and invite it to be cached.
     */
    post: operations['login_api_v1_auth_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Log out
     * @description Revoke the current session and clear its cookies.
     *
     *     Usable with an unrotated temporary password: an account must always be able
     *     to sign out of itself.
     */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * The authenticated user
     * @description Who the caller is, and whether they must change their password first.
     *
     *     Deliberately exempt from the `must_change_password` gate: the web app calls
     *     this before it can know it needs to send the user to the rotation form.
     */
    get: operations['me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change your own password
     * @description Rotate the caller's password, then re-issue their session.
     *
     *     The full sequence, in one transaction: verify `current_password`, apply the
     *     password policy, replace the Argon2id hash, clear `must_change_password`,
     *     reset any lockout counters, revoke **every** existing session of the user,
     *     and issue a fresh one. The new session and CSRF cookies are on this
     *     response, so the caller stays signed in while every other device is signed
     *     out — which is what makes this the right response to a suspected
     *     compromise.
     */
    post: operations['change_password_api_v1_auth_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Report that the process is alive. Touches no dependency, by design.
     */
    get: operations['healthz_api_v1_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/people': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List people
     * @description Paginated directory search.
     *
     *     Admins receive `PersonDetail`. Employees receive `PersonSummary` (masked
     *     identifier, no contact fields) until a person participates in a case
     *     assigned to them — which cannot happen until Phase 5.
     */
    get: operations['list_people_api_v1_people_get'];
    put?: never;
    /**
     * Create a person
     * @description Create a person. The response is always detail — the caller authored it.
     */
    post: operations['create_person_api_v1_people_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/people/{person_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read a person
     * @description Detail when the access predicate holds; summary otherwise. Never 403.
     */
    get: operations['get_person_api_v1_people__person_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update a person
     * @description Edit a person. Employees need an assigned-case participation (Phase 5).
     */
    patch: operations['update_person_api_v1_people__person_id__patch'];
    trace?: never;
  };
  '/api/v1/people/{person_id}/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive a person */
    post: operations['archive_person_api_v1_people__person_id__archive_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/people/{person_id}/cases': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a person's cases
     * @description Cases this person participates in, within the caller's scope.
     *
     *     Always empty in Phase 4: `cases` does not exist. The person must still
     *     exist, so a typo is a 404 rather than a silent empty page.
     */
    get: operations['list_person_cases_api_v1_people__person_id__cases_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/people/{person_id}/unarchive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Unarchive a person */
    post: operations['unarchive_person_api_v1_people__person_id__unarchive_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Report that the dependencies needed to serve traffic are available.
     *
     *     PostgreSQL is the only one in Phase 1 — it is the only dependency a request
     *     currently has. Blob storage joins it in Phase 6, when there is an adapter to
     *     ask.
     */
    get: operations['readyz_api_v1_readyz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description Paginated staff accounts, filterable by free text, role and activation state.
     */
    get: operations['list_users_api_v1_users_get'];
    put?: never;
    /**
     * Create a staff account
     * @description Create an account and return its one-time temporary password (ADR-0026).
     *
     *     The password in this response is the only copy that will ever exist in
     *     plaintext. It is not stored, not logged, not audited and not retrievable
     *     from any other endpoint; if it is lost, the fix is
     *     `POST /users/{user_id}/password-reset`.
     */
    post: operations['create_user_api_v1_users_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/{user_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a staff account */
    get: operations['get_user_api_v1_users__user_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update a staff account
     * @description Change the name, the role or the activation state. Nothing else is settable.
     *
     *     Deactivating revokes every session of the target in the same transaction,
     *     so their next request fails rather than waiting for a cookie to expire.
     */
    patch: operations['update_user_api_v1_users__user_id__patch'];
    trace?: never;
  };
  '/api/v1/users/{user_id}/password-reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a new temporary password
     * @description Replace a user's password with a fresh temporary one (ADR-0026).
     *
     *     This is the whole account-recovery story in Release 1: there is no email
     *     service, so an admin does this and passes the password on out of band. It
     *     clears any lockout, forces rotation at next login, and revokes every
     *     session the user has — including the one they may be using right now.
     */
    post: operations['reset_password_api_v1_users__user_id__password_reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/users/directory': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Staff directory
     * @description Active staff accounts as `{id, full_name, role}`, for assignee pickers.
     *
     *     Unpaginated: this is the internal staff list of a single consultancy, it is
     *     read to populate a dropdown, and paging it would make every caller
     *     reassemble it. Deactivated accounts are omitted — they cannot be given new
     *     work — while historical audit and assignment rows still resolve to them.
     */
    get: operations['list_directory_api_v1_users_directory_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * CurrentUserResponse
     * @description `GET /api/v1/auth/me` — the caller's own identity, and nothing else.
     *
     *     Every field here is already known to the caller. There is no session id, no
     *     token, no hash, no CSRF value and no lockout state: this endpoint is read by
     *     the browser on every page load, and its job is to answer "who am I and may I
     *     proceed", not to describe the session.
     */
    CurrentUserResponse: {
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Must Change Password
       * @description When true, only /auth/me, /auth/password and /auth/logout are usable; every other endpoint answers 403 PASSWORD_CHANGE_REQUIRED.
       */
      must_change_password: boolean;
      role: components['schemas']['UserRole'];
    };
    /**
     * DirectoryEntryResponse
     * @description `GET /api/v1/users/directory` — the three fields an assignee picker needs.
     *
     *     Internal staff only. This is not the people directory: clients, lawyers and
     *     other external parties are `people`, not users.
     */
    DirectoryEntryResponse: {
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      role: components['schemas']['UserRole'];
    };
    /** ErrorBody */
    ErrorBody: {
      /** @description Stable error code; the web app maps it to Hebrew copy. */
      code: components['schemas']['ErrorCode'];
      /** Details */
      details?: components['schemas']['ErrorDetailModel'][];
      /**
       * Message
       * @description English, developer-facing. Never shown to an end user.
       */
      message: string;
      /**
       * Request Id
       * @description Matches the X-Request-ID header and the server log entry.
       */
      request_id: string;
    };
    /**
     * ErrorCode
     * @description Stable, machine-readable error codes.
     *
     *     Codes are added by the phase that can actually raise them, each with a
     *     matching entry in the web message catalog. Phase 1 defined the
     *     infrastructure level; Phase 2 added authentication, authorization and user
     *     administration. Feature codes (`CASE_INVALID_STATUS_TRANSITION`, …) arrive
     *     with their features.
     * @enum {string}
     */
    ErrorCode:
      | 'BAD_REQUEST'
      | 'VALIDATION_ERROR'
      | 'NOT_FOUND'
      | 'METHOD_NOT_ALLOWED'
      | 'CONFLICT'
      | 'TOO_MANY_REQUESTS'
      | 'INTERNAL_ERROR'
      | 'SERVICE_UNAVAILABLE'
      | 'AUTH_REQUIRED'
      | 'AUTH_INVALID_CREDENTIALS'
      | 'AUTH_SESSION_EXPIRED'
      | 'AUTH_ACCOUNT_INACTIVE'
      | 'CSRF_TOKEN_INVALID'
      | 'PASSWORD_CHANGE_REQUIRED'
      | 'PASSWORD_INVALID'
      | 'CURRENT_PASSWORD_INVALID'
      | 'FORBIDDEN'
      | 'USER_NOT_FOUND'
      | 'USER_EMAIL_CONFLICT'
      | 'USER_SELF_DEACTIVATION'
      | 'USER_LAST_ADMIN'
      | 'PERSON_NOT_FOUND'
      | 'PERSON_ACCESS_DENIED'
      | 'PERSON_IDENTIFIER_CONFLICT'
      | 'PERSON_ALREADY_ARCHIVED'
      | 'PERSON_NOT_ARCHIVED';
    /**
     * ErrorDetailModel
     * @description One field-level problem.
     */
    ErrorDetailModel: {
      /**
       * Field
       * @description Dotted path of the offending field, or null for a whole-request problem.
       */
      field?: string | null;
      /**
       * Issue
       * @description Stable, machine-readable description of the problem.
       */
      issue: string;
    };
    /**
     * ErrorEnvelope
     * @description The single shape of every API error.
     */
    ErrorEnvelope: {
      error: components['schemas']['ErrorBody'];
    };
    /**
     * HealthResponse
     * @description Liveness.
     */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: 'ok';
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /**
     * LoginRequest
     * @description Credentials for `POST /api/v1/auth/login`.
     *
     *     `email` is a plain string rather than `EmailStr`, and `password` is only
     *     length-bounded. That is deliberate: a field-level `422` for a malformed
     *     address would answer "no account could possibly exist here" while a
     *     well-formed unknown address gets a `401`, which is the user-enumeration
     *     difference the endpoint exists to avoid (docs/security.md §2). Anything
     *     syntactically wrong simply fails to match an identity and gets the same
     *     uniform failure.
     *
     *     The upper bounds are there so an oversized body is rejected before it
     *     reaches an Argon2 verification, which is 64 MiB of work per call.
     */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** PaginatedResponse[PersonCaseItem] */
    PaginatedResponse_PersonCaseItem_: {
      /** Items */
      items: components['schemas']['PersonCaseItem'][];
      /**
       * Page
       * @description 1-based page number.
       */
      page: number;
      /** Page Size */
      page_size: number;
      /**
       * Total
       * @description Rows matching the filters, ignoring pagination.
       */
      total: number;
    };
    /** PaginatedResponse[PersonReadResponse] */
    PaginatedResponse_PersonReadResponse_: {
      /** Items */
      items: components['schemas']['PersonReadResponse'][];
      /**
       * Page
       * @description 1-based page number.
       */
      page: number;
      /** Page Size */
      page_size: number;
      /**
       * Total
       * @description Rows matching the filters, ignoring pagination.
       */
      total: number;
    };
    /** PaginatedResponse[UserResponse] */
    PaginatedResponse_UserResponse_: {
      /** Items */
      items: components['schemas']['UserResponse'][];
      /**
       * Page
       * @description 1-based page number.
       */
      page: number;
      /** Page Size */
      page_size: number;
      /**
       * Total
       * @description Rows matching the filters, ignoring pagination.
       */
      total: number;
    };
    /**
     * PasswordChangeRequest
     * @description Body for `POST /api/v1/auth/password`.
     *
     *     `new_password` is bounded here and validated against the full policy in
     *     `app.domain.passwords`, which reports every violation at once as
     *     `PASSWORD_INVALID` details.
     */
    PasswordChangeRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /**
     * PersonCaseItem
     * @description A case this person participates in.
     *
     *     Cases do not exist yet. This endpoint always returns an empty page in
     *     Phase 4; the item schema arrives with Phase 5.
     */
    PersonCaseItem: Record<string, never>;
    /**
     * PersonCreateRequest
     * @description Body for `POST /api/v1/people`.
     *
     *     `id_type` and `id_number` are both required together, or both omitted.
     *     Israeli IDs are validated (format + check digit) when the type is
     *     `ISRAELI_ID` (Q7 / ADR-0040).
     */
    PersonCreateRequest: {
      /** Address */
      address?: string | null;
      /** Email */
      email?: string | null;
      /** First Name */
      first_name: string;
      /** Id Number */
      id_number?: string | null;
      id_type?: components['schemas']['PersonIdType'] | null;
      /** Last Name */
      last_name: string;
      /** License Number */
      license_number?: string | null;
      /** Notes */
      notes?: string | null;
      /** Organization Name */
      organization_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Workplace */
      workplace?: string | null;
    };
    /**
     * PersonDetailResponse
     * @description Full operational record. Never serialised without the access predicate.
     *
     *     Create is the documented exception: the caller already authored these values.
     */
    PersonDetailResponse: {
      /** Address */
      address: string | null;
      /** Archived At */
      archived_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Created By
       * Format: uuid
       */
      created_by: string;
      /** Email */
      email: string | null;
      /** First Name */
      first_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Id Number */
      id_number: string | null;
      id_type: components['schemas']['PersonIdType'] | null;
      /** Last Name */
      last_name: string;
      /** License Number */
      license_number: string | null;
      /** Notes */
      notes: string | null;
      /** Organization Name */
      organization_name: string | null;
      /** Phone */
      phone: string | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      representation: 'DETAIL';
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Workplace */
      workplace: string | null;
    };
    /**
     * PersonIdType
     * @description How a person's official identifier is classified (Q7 / ADR-0040).
     *
     *     Organizations are not people: `COMPANY_NUMBER` is deliberately absent.
     *     A person may have no identifier at all — both `id_type` and `id_number`
     *     are then NULL together.
     * @enum {string}
     */
    PersonIdType: 'ISRAELI_ID' | 'PASSPORT' | 'FOREIGN_ID';
    PersonReadResponse:
      | components['schemas']['PersonSummaryResponse']
      | components['schemas']['PersonDetailResponse'];
    /**
     * PersonSummaryResponse
     * @description Masked directory row. The fields an employee may see outside their cases.
     */
    PersonSummaryResponse: {
      /** Archived At */
      archived_at: string | null;
      /** First Name */
      first_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Id Number Masked
       * @description Identifier with all but the last three characters replaced by *.
       */
      id_number_masked: string | null;
      /** Last Name */
      last_name: string;
      /** Organization Name */
      organization_name: string | null;
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      representation: 'SUMMARY';
    };
    /**
     * PersonUpdateRequest
     * @description Body for `PATCH /api/v1/people/{person_id}`.
     *
     *     An explicit allowlist. Omitted fields are left alone. Sending `id_type`
     *     requires `id_number` (and vice versa); both null clears the identifier.
     */
    PersonUpdateRequest: {
      /** Address */
      address?: string | null;
      /** Email */
      email?: string | null;
      /** First Name */
      first_name?: string | null;
      /** Id Number */
      id_number?: string | null;
      id_type?: components['schemas']['PersonIdType'] | null;
      /** Last Name */
      last_name?: string | null;
      /** License Number */
      license_number?: string | null;
      /** Notes */
      notes?: string | null;
      /** Organization Name */
      organization_name?: string | null;
      /** Phone */
      phone?: string | null;
      /** Workplace */
      workplace?: string | null;
    };
    /**
     * ProvisionedUserResponse
     * @description The response to account creation and to an admin password reset (ADR-0026).
     *
     *     `temporary_password` appears in this one response and is never retrievable
     *     again: only its Argon2id hash is stored. The admin passes it to the user out
     *     of band, and the user must change it before any other endpoint will work.
     */
    ProvisionedUserResponse: {
      /**
       * Temporary Password
       * @description Shown exactly once. Not stored in plaintext and not recoverable.
       */
      temporary_password: string;
      user: components['schemas']['UserResponse'];
    };
    /**
     * ReadinessResponse
     * @description Readiness: the dependencies needed to serve traffic answered.
     */
    ReadinessResponse: {
      /**
       * Status
       * @default ready
       * @constant
       */
      status: 'ready';
    };
    /**
     * UserCreateRequest
     * @description Body for `POST /api/v1/users`.
     *
     *     `role` accepts `ADMIN` as well as `EMPLOYEE`: with no self-service password
     *     reset, a firm with one administrator has no way back from a lockout, and
     *     keeping a second `ADMIN` is the documented mitigation (docs/security.md §2).
     */
    UserCreateRequest: {
      /**
       * Email
       * Format: email
       * @description Login identifier. Normalised to lower case and cannot be changed later.
       */
      email: string;
      /** Full Name */
      full_name: string;
      role: components['schemas']['UserRole'];
    };
    /**
     * UserResponse
     * @description A staff account as an administrator sees it.
     *
     *     Built field by field from a `UserView`, never from the ORM row, so adding a
     *     column to `users` cannot publish it here (docs/api.md §1). Absent on
     *     purpose: the identity row and its `secret_hash`, every session, and the
     *     `failed_attempt_count`/`locked_until` lockout counters (docs/security.md §5).
     */
    UserResponse: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Deactivated At */
      deactivated_at: string | null;
      /** Email */
      email: string;
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Is Active
       * @description False once the account has been deactivated.
       */
      is_active: boolean;
      /** Last Login At */
      last_login_at: string | null;
      /** Must Change Password */
      must_change_password: boolean;
      role: components['schemas']['UserRole'];
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * UserRole
     * @description Release 1 has exactly two staff roles (docs/security.md §4).
     *
     *     `CLIENT` and `LAWYER` portals are a later release, and arrive as a
     *     `user_roles` table rather than as members here.
     * @enum {string}
     */
    UserRole: 'ADMIN' | 'EMPLOYEE';
    /**
     * UserUpdateRequest
     * @description Body for `PATCH /api/v1/users/{user_id}`.
     *
     *     An explicit allowlist, not a partial model of the row: `email`,
     *     `must_change_password`, `created_by` and every timestamp are absent because
     *     no administrator may set them directly. Omitted fields are left alone.
     */
    UserUpdateRequest: {
      /**
       * Deactivated
       * @description True deactivates the account and revokes all of its sessions immediately; false reactivates it without restoring the old sessions.
       */
      deactivated?: boolean | null;
      /** Full Name */
      full_name?: string | null;
      role?: components['schemas']['UserRole'] | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type SchemaCurrentUserResponse = components['schemas']['CurrentUserResponse'];
export type SchemaDirectoryEntryResponse = components['schemas']['DirectoryEntryResponse'];
export type SchemaErrorBody = components['schemas']['ErrorBody'];
export type SchemaErrorCode = components['schemas']['ErrorCode'];
export type SchemaErrorDetailModel = components['schemas']['ErrorDetailModel'];
export type SchemaErrorEnvelope = components['schemas']['ErrorEnvelope'];
export type SchemaHealthResponse = components['schemas']['HealthResponse'];
export type SchemaHttpValidationError = components['schemas']['HTTPValidationError'];
export type SchemaLoginRequest = components['schemas']['LoginRequest'];
export type SchemaPaginatedResponsePersonCaseItem =
  components['schemas']['PaginatedResponse_PersonCaseItem_'];
export type SchemaPaginatedResponsePersonReadResponse =
  components['schemas']['PaginatedResponse_PersonReadResponse_'];
export type SchemaPaginatedResponseUserResponse =
  components['schemas']['PaginatedResponse_UserResponse_'];
export type SchemaPasswordChangeRequest = components['schemas']['PasswordChangeRequest'];
export type SchemaPersonCaseItem = components['schemas']['PersonCaseItem'];
export type SchemaPersonCreateRequest = components['schemas']['PersonCreateRequest'];
export type SchemaPersonDetailResponse = components['schemas']['PersonDetailResponse'];
export type SchemaPersonIdType = components['schemas']['PersonIdType'];
export type SchemaPersonReadResponse = components['schemas']['PersonReadResponse'];
export type SchemaPersonSummaryResponse = components['schemas']['PersonSummaryResponse'];
export type SchemaPersonUpdateRequest = components['schemas']['PersonUpdateRequest'];
export type SchemaProvisionedUserResponse = components['schemas']['ProvisionedUserResponse'];
export type SchemaReadinessResponse = components['schemas']['ReadinessResponse'];
export type SchemaUserCreateRequest = components['schemas']['UserCreateRequest'];
export type SchemaUserResponse = components['schemas']['UserResponse'];
export type SchemaUserRole = components['schemas']['UserRole'];
export type SchemaUserUpdateRequest = components['schemas']['UserUpdateRequest'];
export type SchemaValidationError = components['schemas']['ValidationError'];
export type $defs = Record<string, never>;
export interface operations {
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description AUTH_INVALID_CREDENTIALS. The same response for an unknown address, a wrong password, a locked identity and a deactivated account. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description TOO_MANY_REQUESTS — login throttled. */
      429: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CurrentUserResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  change_password_api_v1_auth_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CURRENT_PASSWORD_INVALID, or PASSWORD_INVALID with one details entry per policy violation. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  healthz_api_v1_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  list_people_api_v1_people_get: {
    parameters: {
      query?: {
        archived?: boolean | null;
        page?: number;
        page_size?: number;
        query?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse_PersonReadResponse_'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  create_person_api_v1_people_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonCreateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PersonDetailResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_IDENTIFIER_CONFLICT. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description VALIDATION_ERROR. */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  get_person_api_v1_people__person_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PersonReadResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  update_person_api_v1_people__person_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PersonUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PersonDetailResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_ACCESS_DENIED, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_IDENTIFIER_CONFLICT. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  archive_person_api_v1_people__person_id__archive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN — ADMIN only. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_ALREADY_ARCHIVED. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  list_person_cases_api_v1_people__person_id__cases_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse_PersonCaseItem_'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  unarchive_person_api_v1_people__person_id__unarchive_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        person_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN — ADMIN only. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description PERSON_NOT_ARCHIVED. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  readyz_api_v1_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReadinessResponse'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description A dependency is unavailable. */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  list_users_api_v1_users_get: {
    parameters: {
      query?: {
        is_active?: boolean | null;
        page?: number;
        page_size?: number;
        query?: string | null;
        role?: components['schemas']['UserRole'] | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse_UserResponse_'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  create_user_api_v1_users_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserCreateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProvisionedUserResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description USER_EMAIL_CONFLICT. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  get_user_api_v1_users__user_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description USER_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  update_user_api_v1_users__user_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UserUpdateRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description USER_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description USER_SELF_DEACTIVATION or USER_LAST_ADMIN. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  reset_password_api_v1_users__user_id__password_reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProvisionedUserResponse'];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description FORBIDDEN, CSRF_TOKEN_INVALID or PASSWORD_CHANGE_REQUIRED. */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description USER_NOT_FOUND. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
  list_directory_api_v1_users_directory_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DirectoryEntryResponse'][];
        };
      };
      /** @description No usable session. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
      /** @description Unexpected server error. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorEnvelope'];
        };
      };
    };
  };
}
