"""The append-only business audit trail and per-case activity timeline.

One table serves both: an audit query filters by actor or action, a case
timeline filters by `case_id`. Rows are written by `app.audit.recorder` inside
the service transaction that made the change, so the log cannot disagree with
the data it describes (ADR-0010).

`UPDATE` and `DELETE` are rejected by a database trigger created in the first
migration. Immutability is not a convention here; it is a constraint.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    Uuid,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
from app.models.mixins import UUIDPrimaryKeyMixin


class ActivityLog(UUIDPrimaryKeyMixin, Base):
    __tablename__ = "activity_log"
    __table_args__ = (
        CheckConstraint("btrim(action) <> ''", name="action_not_blank"),
        CheckConstraint("btrim(entity_type) <> ''", name="entity_type_not_blank"),
        CheckConstraint("btrim(description) <> ''", name="description_not_blank"),
        # The four documented read paths (docs/domain-model.md §7). All are
        # plain ascending indexes: PostgreSQL scans them backwards for the
        # `occurred_at DESC` ordering the UI uses, and a DESC index would only
        # add reflection noise to every autogenerated migration diff.
        Index(None, "case_id", "occurred_at"),
        Index(None, "entity_type", "entity_id"),
        Index(None, "actor_user_id", "occurred_at"),
        Index(None, "action", "occurred_at"),
        Index(None, "occurred_at"),
    )

    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    #: `NULL` means the system acted rather than a person — future automation.
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid(), ForeignKey("users.id", ondelete="RESTRICT")
    )
    #: A member of `app.audit.actions.AuditAction`. Deliberately not constrained
    #: by the database: the catalogue grows in every later phase, values are
    #: only ever written through the typed recorder, and a check constraint
    #: naming actions for entities that do not exist yet would be schema noise.
    action: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_type: Mapped[str] = mapped_column(String(64), nullable=False)
    entity_id: Mapped[uuid.UUID | None] = mapped_column(Uuid())
    #: Denormalised so a case timeline is one indexed query. There is no foreign
    #: key yet because `cases` does not exist; Phase 5 adds it additively
    #: (ADR-0030).
    case_id: Mapped[uuid.UUID | None] = mapped_column(Uuid())
    #: English, operator-readable. The UI renders Hebrew from `action` +
    #: `event_metadata`, never from this string (ADR-0014).
    description: Mapped[str] = mapped_column(Text(), nullable=False)
    #: Mapped to the column `metadata`; the Python name differs because
    #: `metadata` is reserved by SQLAlchemy's declarative base.
    event_metadata: Mapped[dict[str, Any]] = mapped_column(
        "metadata",
        JSONB(),
        nullable=False,
        server_default=text("'{}'::jsonb"),
        default=dict,
    )
    #: `{field: {before, after}}` for allowlisted fields only, with sensitive
    #: values redacted (docs/security.md §7).
    changes: Mapped[dict[str, Any] | None] = mapped_column(JSONB())
    #: Correlates a business event with the application log lines of the request
    #: that produced it.
    request_id: Mapped[str | None] = mapped_column(String(64))
    ip_address: Mapped[str | None] = mapped_column(INET())
