"""Column patterns shared by every table.

Primary keys are UUIDs generated by the application (docs/domain-model.md §2):
the value is known before the `INSERT`, which lets a service build a whole
object graph — and its audit rows — in memory before touching the database.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(Uuid(), primary_key=True, default=uuid.uuid4)

    # `Any` because this forwards to SQLAlchemy's declarative constructor, whose
    # keywords are the mapped columns of whichever model is being built.
    def __init__(self, **kwargs: Any) -> None:  # noqa: ANN401
        """Assign the identifier now rather than at flush time.

        A column `default` fires during `INSERT`, which would leave `id` as
        `None` on a newly constructed object — and the promise above is that a
        service can wire up a whole object graph, foreign keys and audit rows
        included, before anything is written. So the key is generated here, in
        Python, and the column default remains as the backstop for a row built
        some other way.
        """
        kwargs.setdefault("id", uuid.uuid4())
        super().__init__(**kwargs)


class TimestampMixin:
    """`created_at` / `updated_at`, both UTC `TIMESTAMPTZ` (ADR-0015).

    The server defaults mean a row written by a migration or by `psql` is
    timestamped too, not only one written through the ORM.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
