"""Column patterns shared by every table.

Primary keys are UUIDs generated by the application (docs/domain-model.md §2):
the value is known before the `INSERT`, which lets a service build a whole
object graph — and its audit rows — in memory before touching the database.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = mapped_column(Uuid(), primary_key=True, default=uuid.uuid4)


class TimestampMixin:
    """`created_at` / `updated_at`, both UTC `TIMESTAMPTZ` (ADR-0015).

    The server defaults mean a row written by a migration or by `psql` is
    timestamped too, not only one written through the ORM.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )
