"""The declarative base and the one `MetaData` Alembic compares against.

The naming convention matters more than it looks: without it PostgreSQL invents
constraint names, autogenerated migrations churn, and a migration that has to
drop a constraint cannot name it. With it, every constraint and index in the
database is predictable from its table and columns (docs/domain-model.md §2).
"""

from __future__ import annotations

from typing import Any, Final

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

NAMING_CONVENTION: Final[dict[str, Any]] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Declarative base for every ORM model in the application."""

    metadata = metadata
