"""The per-request correlation id, carried out of band.

The id is generated by the middleware in `app.api.middleware`, returned to the
caller in `X-Request-ID` and in every error envelope, attached to every log
line, and stored on the audit rows a request writes. Passing it through a
`ContextVar` rather than through every function signature is what keeps the
audit recorder and the logger from needing a `Request` object.
"""

from __future__ import annotations

from contextvars import ContextVar
from uuid import uuid4

_request_id: ContextVar[str | None] = ContextVar("request_id", default=None)


def new_request_id() -> str:
    """A fresh correlation id.

    Always server-generated: an inbound `X-Request-ID` is never trusted,
    because a caller could otherwise collide two unrelated requests in the logs
    or inject arbitrary text into them (ADR-0032).
    """
    return str(uuid4())


def set_request_id(request_id: str) -> None:
    _request_id.set(request_id)


def get_request_id() -> str | None:
    """The current request's id, or `None` outside a request (jobs, scripts, tests)."""
    return _request_id.get()


def reset_request_id() -> None:
    _request_id.set(None)
